### ISSUE TITLE
Anyone Else Having Issues With Data Disappearing?

### ISSUE THREAD

**Issue by jbnance** [amykyta3/enphase-power-logger#7]
Before I take this to the Influx community, I was hoping to check in here and see if anyone else has seen their InfluxDB losing data on a regular basis.  I see multiple days (up to 8 at a time) just disappear.  I'll literally be looking at a graph, hit refresh, and BAM - data that was just there is gone.

I'm running InfluxDB2 version 2.7.1 with a single bucket for both the "high" and "low" data.  My InfluxDB2 configs are bare bones:

**`/etc/default/influxdb2`**
```
INFLUXD_CONFIG_PATH=/etc/influxdb/config.toml
```

**`/etc/influxdb/config.toml`**
```
bolt-path = "/var/lib/influxdb/influxd.bolt"
engine-path = "/var/lib/influxdb/engine"
```

**Comment by sisao** [comment]
Maybe check if your buckets have set a short retention policy:

Via CLI:
https://docs.influxdata.com/influxdb/v2/reference/internals/data-retention/#view-bucket-retention-periods-and-shard-group-durations

or UI:
![image](https://github.com/amykyta3/envoy-logger/assets/514609/6391cb35-f874-4634-b888-d7c864904510)

**Comment by jbnance** [comment]
Thanks for the thoughts.  Unfortunately, my bucket retention is also set to forever.  What's really weird about this situation is that I don't lose all the data from some time back, I just lose chunks of it.  For example:

![2023-09-20 21_20_00-Daily (Envoy Logger) - Grafana — Mozilla Firefox](https://github.com/amykyta3/envoy-logger/assets/4754442/dd609309-d97a-4e2c-9e5d-f43702e72d0f)

See those two empty spots between 8/4-8/16ish and again 9/3ish-9/9?  (I didn't start gathering data until early in July)

So weird... ☹️

**Comment by jbnance** [comment]
I can't find any evidence of anyone else having the same issue, so I'm gonna have to just chalk this one up to something goofed on my side.
